"""Changed lenght of email in customer

Revision ID: 174eb0ccf52f
Revises: ee93e3a80623
Create Date: 2025-12-31 20:04:11.409145

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '174eb0ccf52f'
down_revision: Union[str, Sequence[str], None] = 'ee93e3a80623'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
