"""Added cascade deletion on customer_car

Revision ID: 800c77a6212b
Revises: 174eb0ccf52f
Create Date: 2026-01-02 16:13:15.302603

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '800c77a6212b'
down_revision: Union[str, Sequence[str], None] = '174eb0ccf52f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('customer_car_customer_id_fkey'), 'customer_car', type_='foreignkey')
    op.create_foreign_key(None, 'customer_car', 'customers', ['customer_id'], ['customer_id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'customer_car', type_='foreignkey')
    op.create_foreign_key(op.f('customer_car_customer_id_fkey'), 'customer_car', 'customers', ['customer_id'], ['customer_id'])
    # ### end Alembic commands ###
