"""added workshop logo path

Revision ID: a347227ffc64
Revises: dfa5f3f77bb1
Create Date: 2025-12-09 09:42:29.054978

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a347227ffc64'
down_revision: Union[str, Sequence[str], None] = 'dfa5f3f77bb1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workshops', sa.Column('workshop_logo', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('workshops', 'workshop_logo')
    # ### end Alembic commands ###
